### ISSUE TITLE
phosphor-svelte hangs Vite dev server?

### ISSUE THREAD

**Issue by ninjadev64** [haruaki07/phosphor-svelte#12]
Importing any of the icons into my +page.svelte causes the Vite dev server to be entirely unresponsive - the site loads forever in the browser, updates to files don't trigger an HMR update, and pressing "r" or "q" etc in the terminal do nothing.

Svelte 4.2.2, SvelteKit 1.27.2, Vite 4.5.0, and phosphor-svelte 1.3.0.

**Comment by ninjadev64** [comment]
I am still experiencing very severe delays in load times due to this dependency so it may still be an issue.

**Comment by haruaki07** [comment]
Hello @ninjadev64!, Could you please provide a minimal reproduction repository or a sandbox link? Also, how do you import the icons? The way you import may can affect performance.

You shouldn't import the icons like this `import { Cube } from "phosphor-svelte"`. This is because it will import all the icons during development mode. However, you don't need to worry about this in production mode, as the bundler will optimize the code using tree-shaking.

The recommended way is to import directly the icon component (`import Cube from "phosphor-svelte/lib/Cube"`). It can play nice during dev mode.

**Comment by haruaki07** [comment]
Btw, should I reopen this issue?

**Comment by ninjadev64** [comment]
Yep - using `import { Cube } from "phosphor-svelte";` had the worst impact. However, using `import Cube from "phosphor-svelte/lib/Cube";` had a large impact on its own, as it counts as an extra dependency that Vite has to optimise, which takes a while every time I include a new icon.

Feel free to reopen the issue, but I'm no longer using this dependency as I found it easier to just create a very basic Icon component, as I don't actually use very many icons. Thank you for replying, though!

**Comment by babakfp** [comment]
@ninjadev64 
Hey 🖐️
Can you check out this alternative library and let me know how it performs?
https://github.com/babakfp/phosphor-icons-svelte
Thanks

**Comment by ninjadev64** [comment]
I'm using this lib in another project now with zero issues. No idea what was wrong the first time around. ;)
