### ISSUE TITLE
About your preprocessor

### ISSUE THREAD

**Issue by WarningImHack3r** [haruaki07/phosphor-svelte#24]
Hi there! I stumbled upon your experimental preprocessor someday while I was taking a look at Phosphor for potential future usage.

The problem it's trying to solve is something that was enabled to do manually on `lucide-svelte` a few months ago, so I realized such a thing would be a perfect match for Lucide too.

As a result, I made https://github.com/WarningImHack3r/vite-plugin-lucide-preprocess, which I'm pretty proud of for my first-ever Vite plugin! All the info and context are in the README.

So today I open this issue as a sort of discussion about whether you'd want (or I) to rewrite your preprocessor my way: it's tested, stable now and works very well with none of the caveats of a Svelte-only plugin.

If you're interested in that, I think it'd be even better to share a common base between all icon libraries (and Vite-based frameworks) that we could reuse so we take advantage of feature parity.

Or maybe not, because the plugin itself is not even that big. What do you think?

**Comment by haruaki07** [comment]
Hi, thanks for reaching out regarding my preprocessor.

You did a great job, @WarningImHack3r! You made a nice plugin. I see that your code is well-tested, and you are using the Vite plugin instead of the Svelte preprocessor, which is great for other UI libraries or frameworks like React, Vue, etc., if they face the same issues. It can even support other icon libraries. I find it interesting to contribute to your plugin.

One thing I noticed after I tried your plugin, following the instructions on the readme, is that Vite still prebundled the icons and it will slow down the dev server. The plugin itself is working, but by excluding the lucide-svelte from prebundling. Or maybe this is just happened on my PC. Read this for further information: https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#rewriting-imports-with-plugins-or-preprocessors.

But for now, I just stick with the current approach, using the Svelte preprocessor to rewrite the import style, as this is just work and has been working well so far. Maybe I should remove the "experimental" notice from the readme.

**Comment by WarningImHack3r** [comment]
Thanks for your answer!
From my testing I'm pretty sure the dev server slowdown are solved, because I can see in the console Vite optimizing individual icons despite my imports being the global ones; and most importantly: with my plugin I don't see anymore the large raw lucide_icons.js import in the node_modules in the browser while inspecting the Sources, but I do see it when my plugin is disabled.

But despite it being seemingly functional, I'm indeed pretty sure I'm doing something wrong as I seem to break a few rules of the link you just gave me: I'll take a closer look at that!

Thanks

**Comment by WarningImHack3r** [comment]
Ok, after further reading, it seems that (as you said) I'm doing it correctly. However, Vite is still loading the whole thing despite _not serving it_, and that'd be the reason why I don't see it from the browser, but you still feel the slowness.

Am I correct about this @dominikg? As you wrote that part of the documentation, can you confirm/guide me through what I should do? Is there a way not to need the user to exclude the library from pre-bundling?
